version: '3'

services:
  # اطمینان از راه‌اندازی شدن کامل سرویس‌های وابسته
  backend:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # تنظیم سرویس MySQL با پارامترهای health check
  mysql:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puserpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password

  # تنظیم سرویس Redis با health check
  redis:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s

  # تنظیمات بیشتر برای سرویس تشخیص چهره
  face-detection:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - BACKEND_URL=http://backend:3001
      - FLASK_ENV=production
    # بیشتر کردن زمان انتظار برای ساخت تصویر
    build:
      shm_size: 2gb
    # نصب curl برای health check
    healthcheck:
      test: sh -c "apt-get update && apt-get install -y curl && curl -f http://localhost:5000/health || exit 1" 