version: '3'

services:
  # سرویس Next.js (فرانت‌اند)
  frontend:
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./certs:/certs
    restart: unless-stopped
    depends_on:
      - backend

  # سرویس Nest.js (بک‌اند)
  backend:
    build:
      context: ./nest
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    env_file:
      - ./nest/.env
    depends_on:
      - mysql

  # سرویس دیتابیس MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 